name: logv3lpf

dependencies:
    - python==3.8.3
    - pip
    - pip:
        - pandas
        - numpy
        - matplotlib
        - seaborn
        - opendssdirect.py
        - networkx
        - scipy
