name: pysoda

dependencies:
    - python==3.8.3
    - pip
    - pip:
        - pandas
        - numpy
        - matplotlib
        - seaborn
        - opendssdirect-py == 0.5.0
        - networkx
        - scipy
